### ISSUE TITLE
threading error with Django 3?

### ISSUE THREAD

**Issue by tomcounsell** [praekelt/django-ultracache#7]
I updated from Django 2.2 to Django 3.0.6 and getting this error on my API endpoints
```
  File "/.../lib/python3.6/site-packages/ultracache/monkey.py", line 160, in wrapped
    cache_meta(_thread_locals.ultracache_recorder, cache_key, request=request)
AttributeError: '_thread._local' object has no attribute 'ultracache_recorder'
```

**Comment by hedleyroos** [comment]
Hi. I haven't used it on Django 3 yet so will create a test for it and replicate the issue.

**Comment by hedleyroos** [comment]
Hi @tomcounsell . I haven't ported it to Django 3 yet but will give it a go soon.

**Comment by hedleyroos** [comment]
The project has moved to https://github.com/hedleyroos/django-ultracache. I have created a test for Django 3 and DRF 3.11. Would you mind testing the latest code please?
